import = ["~/.config/alacritty/themes/themes/rose-pine.toml"]

[font]

normal.family = "MesloLGS Nerd Font"
bold.family = "MesloLGS Nerd Font"
italic.family = "MesloLGS Nerd Font"
bold_italic.family = "MesloLGS Nerd Font"
size = 14

[keyboard]

bindings = [
	{ key = "ArrowLeft", mods = "Command", action = "SelectPreviousTab" },
	{ key = "ArrowRight", mods = "Command", action = "SelectNextTab" },
  { key = "N", mods = "Command | Control", command = { program = "/opt/homebrew/bin/alacritty", args = [ "msg", "create-window", "-e", "arch", "-x86_64", "/usr/local/bin/zsh", "--login" ] } }
]

[window]

decorations = "Full"
