#
# macOS Specific
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
  export PATH=/opt/homebrew/bin:$PATH
  export HOMEBREW_CASK_OPTS="--no-quarantine"
  export GHIDRA_INSTALL_DIR=$(echo $(brew --prefix)/Caskroom/ghidra/*/*)
  export PATH="$(brew --prefix make)/libexec/gnubin:$PATH"
  export MonkeyDevPath=/opt/MonkeyDev
  export MonkeyDevDeviceIP=
  export PATH=/opt/MonkeyDev/bin:$PATH
fi

#
# Editors
#

export EDITOR='nano'
export VISUAL='nano'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
cdpath=(
  $cdpath
)

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# NVM
#

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

#
## Theos
#

export THEOS=$HOME/theos

#
# Cargo
#

export PATH=$HOME/.cargo/bin:$PATH
