source $(brew --prefix)/share/antidote/antidote.zsh
antidote bundle < ~/.zsh_plugins > ~/.zsh_plugins.zsh
source ~/.zsh_plugins.zsh
zstyle :prompt:pure:path color cyan
zstyle :prompt:pure:prompt:success color green
zstyle ':prompt:pure:git:*' color magenta
zstyle :prompt:pure:virtualenv color yellow
source $HOME/.bash_aliases
