command -v exa > /dev/null
if [[ $? -eq 0 ]]; then
  alias ls="exa -l --icons --git"
else
  alias ls="ls -l --color=auto"
fi

command -v codium > /dev/null
if [[ $? -eq 0 ]]; then
  alias code="codium"
fi

alias clear="clear && printf \"\e[H\e[3J\""