if [[ "$OSTYPE" == darwin* ]]; then
  if [[ $(arch) == arm64 ]]; then
    export PATH="$PATH:/opt/homebrew/bin"
  else
    export PATH="$PATH:/usr/local/bin"
  fi
else
  export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"
fi

source $HOME/.bash_aliases